#!/usr/bin/env sh

# Git commitが完了した直後に実行

# 通知は無効化
# NOTIFIER="./scripts/notify.sh"
# COMMIT_MSG=$(git log -1 --pretty=%B)
# if [ -f "$NOTIFIER" ]; then
#   "$NOTIFIER" done "コミット完了" "$COMMIT_MSG" 2>/dev/null &
# fi
